apiVersion: v1
kind: ResourceQuota
metadata:
  name: tenant-quota
  namespace: tenant1
spec:
  hard:
    pods: "20"
    services: "10"
    persistentvolumeclaims: "5"
    configmaps: "20"
    secrets: "20"
    requests.cpu: "1"
    limits.cpu: "1"
    requests.memory: "2Gi"
    limits.memory: "2Gi"
    requests.storage: "20Gi"