apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tenant1-app
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "11"
spec:
  project: tenant1
  source:
    repoURL: https://github.com/smescloud/tenant1-app-config.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: tenant1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false