apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eu001-cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: platform-infra
  sources:
    - repoURL: https://charts.jetstack.io
      chart: cert-manager
      targetRevision: v1.18.2
      helm:
        releaseName: cert-manager
        valueFiles:
          - $values/platform/infra/cert-manager/values-base.yaml
          - $values/clusters/eu001/overlays/cert-manager-values.yaml
    - repoURL: https://github.com/smescloud/platformops.git
      targetRevision: eu001-release1
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
