apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eu001-coredns
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: https://github.com/smescloud/platformops.git
    targetRevision: main
    path: platform/infra/coredns/base
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true