apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eu001-traefik
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  sources:
    - repoURL: https://traefik.github.io/charts
      chart: traefik
      targetRevision: 34.4.0
      helm:
        releaseName: traefik
        valueFiles:
          - $values/platform/infra/traefik/values-base.yaml
          - $values/clusters/eu001/overlays/traefik-values.yaml
    - repoURL: https://github.com/smescloud/platformops.git
      targetRevision: eu001-r0001
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
