apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eu001-traefik-extra
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/smescloud/platformops.git
    targetRevision: main
    path: platform/infra/traefik/extra-manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
