apiVersion: v1
kind: LimitRange
metadata:
  name: tenant-limits
  namespace: nextnodepostgres
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: "100m"
        memory: "128Mi"
      default:
        cpu: "250m"
        memory: "256Mi"
      min:
        cpu: "50m"
        memory: "64Mi"
      max:
        cpu: "1"
        memory: "2Gi"
    - type: PersistentVolumeClaim
      min:
        storage: "1Gi"
      max:
        storage: "40Gi"