apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tenant-poweruser-binding
  namespace: nextnodepostgres
subjects:
  - kind: Group
    name: oidc:nextnodepostgres-k8s
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: tenant-poweruser
  apiGroup: rbac.authorization.k8s.io