apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - infra-apps/namespaces.yaml
  - infra-apps/coredns.yaml
  - infra-apps/cert-manager.yaml
  - infra-apps/traefik-crds.yaml
  - infra-apps/traefik.yaml
  - infra-apps/cert-issuers.yaml
  - infra-apps/longhorn.yaml
  - infra-apps/monitoring-crds.yaml
  - infra-apps/monitoring.yaml
  - infra-apps/auth.yaml
  - infra-apps/argocd-access.yaml