apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform-infra
  namespace: argocd
spec:
  description: Platform infrastructure project for eu001 root and infra apps
  sourceRepos:
    - https://github.com/smescloud/platformops.git
    - https://charts.jetstack.io
    - https://charts.longhorn.io
    - https://prometheus-community.github.io/helm-charts
  destinations:
    - namespace: argocd
      server: https://kubernetes.default.svc
    - namespace: default
      server: https://kubernetes.default.svc
    - namespace: cert-manager
      server: https://kubernetes.default.svc
    - namespace: traefik-system
      server: https://kubernetes.default.svc
    - namespace: longhorn-system
      server: https://kubernetes.default.svc
    - namespace: monitoring
      server: https://kubernetes.default.svc
    - namespace: auth
      server: https://kubernetes.default.svc
    - namespace: kube-system
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'