apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: traefik-crd-reader
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - secrets
      - nodes
      - configmaps
      - namespaces
    verbs:
      - get
      - list
      - watch

  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get

  - apiGroups:
      - discovery.k8s.io
    resources:
      - endpointslices
    verbs:
      - list
      - watch

  - apiGroups:
      - networking.k8s.io
      - extensions
    resources:
      - ingresses
      - ingressclasses
    verbs:
      - get
      - list
      - watch

  - apiGroups:
      - networking.k8s.io
      - extensions
    resources:
      - ingresses/status
    verbs:
      - update

  - apiGroups:
      - traefik.io
    resources:
      - ingressroutes
      - ingressroutetcps
      - ingressrouteudps
      - middlewares
      - middlewaretcps
      - tlsoptions
      - tlsstores
      - traefikservices
      - serverstransports
      - serverstransporttcps
    verbs:
      - get
      - list
      - watch